### ISSUE TITLE
Using worldedit wand's right click throw alot of console errors

### ISSUE THREAD

**Issue by webdo** [UsainSrht/Sit#1]
Hi, amazing little plugin, thank you for sharing it!
It works great, but i get alot of console errors thrown when i use the right click from WorldEdit's wand.

I do not code in java but  from the logs i would think that just checking if getHand() is null would fix the issue, i might be wrong tho!

Here is the said log, it just repeats this many many times.

`ERROR19:06:28
Could not pass event PlayerInteractEvent to Sit v1.2
Console19:06:28
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.EquipmentSlot.equals(Object)" because the return value of "org.bukkit.event.player.PlayerInteractEvent.getHand()" is null
at com.purpurmc.sit.Events.onSit(Events.java:33) ~[sit-1.2.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor114.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:git-Purpur-1861]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:545) ~[purpur-1.19.3.jar:git-Purpur-1861]
at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:502) ~[purpur-1.19.3.jar:git-Purpur-1861]
at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:497) ~[purpur-1.19.3.jar:git-Purpur-1861]
at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:492) ~[purpur-1.19.3.jar:git-Purpur-1861]
at net.minecraft.world.level.block.PressurePlateBlock.getSignalStrength(PressurePlateBlock.java:86) ~[?:?]
at net.minecraft.world.level.block.BasePressurePlateBlock.checkPressed(BasePressurePlateBlock.java:82) ~[?:?]
at net.minecraft.world.level.block.BasePressurePlateBlock.entityInside(BasePressurePlateBlock.java:75) ~[?:?]
at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.entityInside(BlockBehaviour.java:1049) ~[?:?]
at net.minecraft.world.entity.Entity.checkInsideBlocks(Entity.java:1534) ~[purpur-1.19.3.jar:git-Purpur-1861]
at net.minecraft.world.entity.Entity.tryCheckInsideBlocks(Entity.java:1238) ~[purpur-1.19.3.jar:git-Purpur-1861]
at net.minecraft.world.entity.Entity.move(Entity.java:1165) ~[purpur-1.19.3.jar:git-Purpur-1861]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1585) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.handle(ServerboundMovePlayerPacket.java:88) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.3.jar:git-Purpur-1861]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[purpur-1.19.3.jar:git-Purpur-1861]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.3.jar:git-Purpur-1861]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[purpur-1.19.3.jar:git-Purpur-1861]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[purpur-1.19.3.jar:git-Purpur-1861]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1314) ~[purpur-1.19.3.jar:git-Purpur-1861]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[purpur-1.19.3.jar:git-Purpur-1861]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[purpur-1.19.3.jar:git-Purpur-1861]
at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by webdo** [comment]
See pull request #2.

**Comment by UsainSrht** [comment]
I was aware of this but had not have time to fix. Will review the pr. Thank you.
